import { damageComponent, standardDamage } from '../../combat/DamageComponentPresets';
import { CombatSkillDefinition } from './CombatSkillDefinition';

/** Skills exclusivas de monstros — cooldowns e prioridade de alvo calibrados para inimigos. */
export const ENEMY_MONSTER_COMBAT_SKILL_CATALOG: CombatSkillDefinition[] = [
  {
    skillId: 'wild_bite',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 72,
    usePriority: 45,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 5,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'goblin_stab',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 75,
    usePriority: 55,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 6,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'orc_smash',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 82,
    usePriority: 70,
    initialCooldown: 2,
    cooldownTurns: 4,
    basePower: 8,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'poison_spit',
    kind: 'damage',
    damageComponents: standardDamage('chaos', 'single'),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 78,
    usePriority: 52,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 5,
    powerPerRank: 0,
    attributeFactor: 0,
    onHitDot: { element: 'chaos', damagePerTurn: 3, durationTurns: 3, applyChance: 0.7 },
  },
  {
    skillId: 'ground_slam',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 75,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 7,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'regenerate',
    kind: 'heal_ally',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 92,
    usePriority: 60,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 15,
    powerPerRank: 0,
    attributeFactor: 0,
    healConditionThreshold: 0.6,
  },
  {
    skillId: 'slime_acid',
    kind: 'damage',
    damageComponents: standardDamage('chaos', 'single'),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 70,
    usePriority: 40,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 4,
    powerPerRank: 0,
    attributeFactor: 0,
    onHitDot: { element: 'chaos', damagePerTurn: 2, durationTurns: 4, applyChance: 0.85 },
  },
  {
    skillId: 'wraith_drain',
    kind: 'damage',
    damageComponents: standardDamage('chaos', 'single'),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 80,
    usePriority: 75,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 6,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'wraith_curse',
    kind: 'debuff_defense',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 76,
    usePriority: 68,
    initialCooldown: 0,
    cooldownTurns: 6,
    basePower: 3,
    powerPerRank: 0,
    attributeFactor: 0,
    effectDurationTurns: 2,
  },
  {
    skillId: 'dragon_breath',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'all', {
      extras: [damageComponent('physical', 'aoe', 0.1)],
    }),
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 4,
    cooldownTurns: 6,
    basePower: 12,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'dragon_bite',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    targetPriorityPercent: 85,
    usePriority: 80,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 8,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'saci_fire',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 78,
    usePriority: 82,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 11,
    powerPerRank: 0,
    attributeFactor: 0,
  },
  {
    skillId: 'saci_wind',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'all', { delivery: 'aoe' }),
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 78,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 7,
    powerPerRank: 0,
    attributeFactor: 0,
  },
];
