import { Hero } from '../../entities/Hero';
import { CombatSkillDefinition } from './CombatSkillDefinition';

export const BASIC_ATTACK_SKILL: CombatSkillDefinition = {
  skillId: 'basic_attack',
  kind: 'damage_physical',
  targetPool: 'enemies',
  targetScope: 'single',
  targetPriority: 'lowest_hp_percent',
  usePriority: 0,
  initialCooldown: 0,
  cooldownTurns: 0,
  basePower: 0,
  powerPerRank: 0,
  attributeFactor: 0,
  usesAttackStat: true,
};

export const HERO_COMBAT_SKILL_CATALOG: CombatSkillDefinition[] = [
  {
    skillId: 'minor_heal',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 100,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 12,
    powerPerRank: 8,
    attributeFactor: 1.2,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'fireball',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 2,
    cooldownTurns: 2,
    basePower: 10,
    powerPerRank: 6,
    attributeFactor: 1.5,
  },
  {
    skillId: 'arcane_bolt',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 80,
    initialCooldown: 0,
    cooldownTurns: 1,
    basePower: 8,
    powerPerRank: 4,
    attributeFactor: 1.3,
  },
  {
    skillId: 'smite',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 75,
    initialCooldown: 0,
    cooldownTurns: 1,
    basePower: 7,
    powerPerRank: 5,
    attributeFactor: 1.2,
  },
  {
    skillId: 'arcane_touch',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 50,
    initialCooldown: 0,
    cooldownTurns: 0,
    basePower: 5,
    powerPerRank: 3,
    attributeFactor: 1.0,
  },
  {
    skillId: 'shield_bash',
    kind: 'damage_physical',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 60,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 6,
    powerPerRank: 4,
    attributeFactor: 0.8,
  },
  {
    skillId: 'power_attack',
    kind: 'damage_physical',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 40,
    initialCooldown: 0,
    cooldownTurns: 1,
    basePower: 4,
    powerPerRank: 3,
    attributeFactor: 0.6,
  },
  {
    skillId: 'oracle_mend',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 110,
    initialCooldown: 0,
    cooldownTurns: 3,
    basePower: 18,
    powerPerRank: 10,
    attributeFactor: 1.4,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'oracle_sanctuary',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 105,
    initialCooldown: 3,
    cooldownTurns: 4,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 1.0,
    healConditionThreshold: 0.75,
  },
  {
    skillId: 'guardian_resolve',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 95,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 10,
    powerPerRank: 6,
    attributeFactor: 0.8,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'reaver_cleave',
    kind: 'damage_physical',
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 0,
    cooldownTurns: 3,
    basePower: 12,
    powerPerRank: 6,
    attributeFactor: 1.0,
  },
  {
    skillId: 'reaver_fury',
    kind: 'damage_physical',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 82,
    initialCooldown: 1,
    cooldownTurns: 2,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 0.9,
  },
  {
    skillId: 'guardian_strike',
    kind: 'damage_physical',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 78,
    initialCooldown: 0,
    cooldownTurns: 1,
    basePower: 9,
    powerPerRank: 5,
    attributeFactor: 0.85,
  },
  {
    skillId: 'pyro_inferno',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 92,
    initialCooldown: 2,
    cooldownTurns: 3,
    basePower: 14,
    powerPerRank: 7,
    attributeFactor: 1.6,
  },
  {
    skillId: 'pyro_ember',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 0,
    cooldownTurns: 1,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 1.3,
  },
  {
    skillId: 'arcane_surge',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 91,
    initialCooldown: 1,
    cooldownTurns: 2,
    basePower: 13,
    powerPerRank: 6,
    attributeFactor: 1.5,
  },
  {
    skillId: 'arcane_focus',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 87,
    initialCooldown: 0,
    cooldownTurns: 1,
    basePower: 9,
    powerPerRank: 5,
    attributeFactor: 1.2,
  },
  {
    skillId: 'inquisitor_judgment',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 11,
    powerPerRank: 6,
    attributeFactor: 1.4,
  },
  {
    skillId: 'inquisitor_flame',
    kind: 'damage_magic',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 83,
    initialCooldown: 0,
    cooldownTurns: 1,
    basePower: 8,
    powerPerRank: 4,
    attributeFactor: 1.1,
  },
];

const heroSkillMap = new Map(HERO_COMBAT_SKILL_CATALOG.map((skill) => [skill.skillId, skill]));

export function getHeroCombatSkill(skillId: string): CombatSkillDefinition | undefined {
  if (skillId === 'basic_attack') return BASIC_ATTACK_SKILL;
  return heroSkillMap.get(skillId);
}

export function listHeroCombatSkills(hero: Hero): CombatSkillDefinition[] {
  const props = hero.toProps();
  const equipped = props.equippedSkillIds
    .filter((skillId) => (props.skillRanks[skillId] ?? 0) >= 1)
    .map((skillId) => heroSkillMap.get(skillId))
    .filter((skill): skill is CombatSkillDefinition => skill !== undefined);

  return [BASIC_ATTACK_SKILL, ...equipped];
}
