import { damageComponent, standardDamage } from '../../combat/DamageComponentPresets';
import { Hero } from '../../entities/Hero';
import { BASIC_ATTACK_SKILL } from './BasicAttackSkill';
import { CombatSkillDefinition } from './CombatSkillDefinition';

export { BASIC_ATTACK_SKILL } from './BasicAttackSkill';

export const HERO_COMBAT_SKILL_CATALOG: CombatSkillDefinition[] = [
  BASIC_ATTACK_SKILL,
  {
    skillId: 'blessing',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 72,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 4,
    powerPerRank: 2,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'minor_heal',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 100,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 12,
    powerPerRank: 8,
    attributeFactor: 1.2,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'fireball',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 4,
    cooldownTurns: 4,
    basePower: 10,
    powerPerRank: 6,
    attributeFactor: 1.5,
    onHitDot: { element: 'fire', damagePerTurn: 5, durationTurns: 3, applyChance: 0.6 },
  },
  {
    skillId: 'arcane_bolt',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 80,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 8,
    powerPerRank: 4,
    attributeFactor: 1.3,
  },
  {
    skillId: 'smite',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single', {
      delivery: 'melee',
      extras: [damageComponent('physical', 'melee', 0.3)],
    }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 75,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 7,
    powerPerRank: 5,
    attributeFactor: 1.2,
  },
  {
    skillId: 'arcane_touch',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 50,
    initialCooldown: 0,
    cooldownTurns: 0,
    basePower: 5,
    powerPerRank: 3,
    attributeFactor: 1.0,
  },
  {
    skillId: 'thrust',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 60,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 6,
    powerPerRank: 4,
    attributeFactor: 0.8,
  },
  {
    skillId: 'power_attack',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 90,
    usePriority: 40,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 4,
    powerPerRank: 3,
    attributeFactor: 0.6,
  },
  {
    skillId: 'sag_clr_light',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 82,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 9,
    powerPerRank: 5,
    attributeFactor: 1.25,
  },
  {
    skillId: 'sag_clr_smite',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 80,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 1.3,
  },
  {
    skillId: 'sag_clr_ward',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 73,
    initialCooldown: 2,
    cooldownTurns: 8,
    basePower: 4,
    powerPerRank: 2,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'sag_alt_radiance',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 108,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 16,
    powerPerRank: 8,
    attributeFactor: 1.3,
    healConditionThreshold: 0.88,
  },
  {
    skillId: 'sag_alt_chorus',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 77,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 5,
    powerPerRank: 2,
    attributeFactor: 0.55,
    effectDurationTurns: 3,
  },
  {
    skillId: 'sag_alt_sanctuary',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 104,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 1.0,
    healConditionThreshold: 0.78,
  },
  {
    skillId: 'sag_san_grace',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 112,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 20,
    powerPerRank: 10,
    attributeFactor: 1.45,
    healConditionThreshold: 0.9,
  },
  {
    skillId: 'sag_san_judgment',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 91,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 15,
    powerPerRank: 7,
    attributeFactor: 1.55,
  },
  {
    skillId: 'sag_san_benediction',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 84,
    initialCooldown: 4,
    cooldownTurns: 10,
    basePower: 7,
    powerPerRank: 3,
    attributeFactor: 0.7,
    effectDurationTurns: 4,
  },
  {
    skillId: 'vid_clr_renew',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 109,
    initialCooldown: 0,
    cooldownTurns: 6,
    basePower: 15,
    powerPerRank: 8,
    attributeFactor: 1.35,
    healConditionThreshold: 0.87,
  },
  {
    skillId: 'vid_clr_bloom',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 102,
    initialCooldown: 2,
    cooldownTurns: 8,
    basePower: 8,
    powerPerRank: 4,
    attributeFactor: 0.95,
    healConditionThreshold: 0.8,
  },
  {
    skillId: 'vid_clr_touch',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 111,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 12,
    powerPerRank: 6,
    attributeFactor: 1.2,
    healConditionThreshold: 0.92,
  },
  {
    skillId: 'vid_gua_aegis',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 75,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 5,
    powerPerRank: 2,
    attributeFactor: 0.55,
    effectDurationTurns: 3,
  },
  {
    skillId: 'vid_gua_pulse',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 106,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 12,
    powerPerRank: 6,
    attributeFactor: 1.1,
    healConditionThreshold: 0.82,
  },
  {
    skillId: 'vid_gua_spring',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 110,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 18,
    powerPerRank: 9,
    attributeFactor: 1.4,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'vid_fil_dawn',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 113,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 17,
    powerPerRank: 8,
    attributeFactor: 1.4,
    healConditionThreshold: 0.88,
  },
  {
    skillId: 'vid_fil_aurora',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 107,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 14,
    powerPerRank: 7,
    attributeFactor: 1.25,
    healConditionThreshold: 0.75,
  },
  {
    skillId: 'vid_fil_rebirth',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 115,
    initialCooldown: 6,
    cooldownTurns: 10,
    basePower: 24,
    powerPerRank: 12,
    attributeFactor: 1.5,
    healConditionThreshold: 0.65,
  },
  {
    skillId: 'oracle_mend',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 110,
    initialCooldown: 0,
    cooldownTurns: 6,
    basePower: 18,
    powerPerRank: 10,
    attributeFactor: 1.4,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'oracle_sanctuary',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 105,
    initialCooldown: 6,
    cooldownTurns: 8,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 1.0,
    healConditionThreshold: 0.75,
  },
  {
    skillId: 'mil_guer_cleave',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 84,
    initialCooldown: 0,
    cooldownTurns: 6,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 0.9,
  },
  {
    skillId: 'mil_guer_hold',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 70,
    initialCooldown: 0,
    cooldownTurns: 6,
    basePower: 3,
    powerPerRank: 2,
    attributeFactor: 0.4,
    effectDurationTurns: 2,
  },
  {
    skillId: 'mil_guer_rally',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 76,
    initialCooldown: 2,
    cooldownTurns: 8,
    basePower: 4,
    powerPerRank: 2,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'mil_cap_order',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 80,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 5,
    powerPerRank: 3,
    attributeFactor: 0.6,
    effectDurationTurns: 3,
  },
  {
    skillId: 'mil_cap_phalanx',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'highest_hp_percent',
    usePriority: 74,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 4,
    powerPerRank: 2,
    attributeFactor: 0.5,
    effectDurationTurns: 2,
  },
  {
    skillId: 'mil_cap_lance',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    targetPriorityPercent: 80,
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 12,
    powerPerRank: 6,
    attributeFactor: 1.0,
  },
  {
    skillId: 'mil_gen_decree',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 92,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 16,
    powerPerRank: 8,
    attributeFactor: 1.1,
  },
  {
    skillId: 'mil_gen_banner',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 4,
    cooldownTurns: 10,
    basePower: 6,
    powerPerRank: 3,
    attributeFactor: 0.7,
    effectDurationTurns: 4,
  },
  {
    skillId: 'mil_gen_siege',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 14,
    powerPerRank: 7,
    attributeFactor: 1.0,
  },
  {
    skillId: 'mar_gla_slash',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 83,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 8,
    powerPerRank: 4,
    attributeFactor: 0.85,
  },
  {
    skillId: 'mar_gla_feint',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 68,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 3,
    powerPerRank: 2,
    attributeFactor: 0.4,
    effectDurationTurns: 2,
  },
  {
    skillId: 'mar_gla_bleed',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 81,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 7,
    powerPerRank: 4,
    attributeFactor: 0.75,
    onHitDot: { element: 'chaos', damagePerTurn: 4, durationTurns: 3, applyChance: 0.75 },
  },
  {
    skillId: 'mar_mes_flow',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 87,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 11,
    powerPerRank: 5,
    attributeFactor: 0.95,
  },
  {
    skillId: 'mar_mes_zen',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 72,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 4,
    powerPerRank: 2,
    attributeFactor: 0.45,
    effectDurationTurns: 3,
  },
  {
    skillId: 'mar_mes_rebuke',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 0.9,
  },
  {
    skillId: 'mar_cam_crown',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 94,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 18,
    powerPerRank: 8,
    attributeFactor: 1.15,
  },
  {
    skillId: 'mar_cam_cyclone',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 91,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 13,
    powerPerRank: 6,
    attributeFactor: 1.0,
  },
  {
    skillId: 'mar_cam_glory',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 79,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 14,
    powerPerRank: 7,
    attributeFactor: 0.8,
    healConditionThreshold: 0.9,
  },
  {
    skillId: 'arc_mag_bolt',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 9,
    powerPerRank: 5,
    attributeFactor: 1.3,
  },
  {
    skillId: 'arc_mag_weave',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 70,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 3,
    powerPerRank: 2,
    attributeFactor: 0.45,
    effectDurationTurns: 2,
  },
  {
    skillId: 'arc_mag_ward',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 74,
    initialCooldown: 2,
    cooldownTurns: 8,
    basePower: 4,
    powerPerRank: 2,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'arc_arq_nova',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 11,
    powerPerRank: 6,
    attributeFactor: 1.4,
  },
  {
    skillId: 'arc_arq_rift',
    kind: 'damage',
    damageComponents: standardDamage('chaos', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 2,
    cooldownTurns: 4,
    basePower: 13,
    powerPerRank: 6,
    attributeFactor: 1.5,
  },
  {
    skillId: 'arc_arq_bind',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 72,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 4,
    powerPerRank: 2,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'arc_imp_decree',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 93,
    initialCooldown: 4,
    cooldownTurns: 6,
    basePower: 16,
    powerPerRank: 8,
    attributeFactor: 1.7,
  },
  {
    skillId: 'arc_imp_crown',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 4,
    cooldownTurns: 10,
    basePower: 7,
    powerPerRank: 3,
    attributeFactor: 0.75,
    effectDurationTurns: 4,
  },
  {
    skillId: 'arc_imp_storm',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 91,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 14,
    powerPerRank: 7,
    attributeFactor: 1.55,
  },
  {
    skillId: 'inn_fei_spark',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 84,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 8,
    powerPerRank: 4,
    attributeFactor: 1.2,
  },
  {
    skillId: 'inn_fei_whisper',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 69,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 3,
    powerPerRank: 2,
    attributeFactor: 0.4,
    effectDurationTurns: 2,
  },
  {
    skillId: 'inn_fei_flame',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 87,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 1.35,
    onHitDot: { element: 'fire', damagePerTurn: 4, durationTurns: 2 },
  },
  {
    skillId: 'inn_sob_comet',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 89,
    initialCooldown: 2,
    cooldownTurns: 6,
    basePower: 12,
    powerPerRank: 6,
    attributeFactor: 1.45,
  },
  {
    skillId: 'inn_sob_veil',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 76,
    initialCooldown: 2,
    cooldownTurns: 8,
    basePower: 5,
    powerPerRank: 2,
    attributeFactor: 0.55,
    effectDurationTurns: 3,
  },
  {
    skillId: 'inn_sob_lance',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 12,
    powerPerRank: 6,
    attributeFactor: 1.4,
  },
  {
    skillId: 'inn_fil_ether',
    kind: 'damage',
    damageComponents: standardDamage('chaos', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 92,
    initialCooldown: 2,
    cooldownTurns: 4,
    basePower: 15,
    powerPerRank: 7,
    attributeFactor: 1.65,
  },
  {
    skillId: 'inn_fil_storm',
    kind: 'damage',
    damageComponents: standardDamage('chaos', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 13,
    powerPerRank: 7,
    attributeFactor: 1.5,
  },
  {
    skillId: 'inn_fil_ascend',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 78,
    initialCooldown: 4,
    cooldownTurns: 8,
    basePower: 14,
    powerPerRank: 7,
    attributeFactor: 0.85,
    healConditionThreshold: 0.95,
  },
  {
    skillId: 'pyro_inferno',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'all', {
      extras: [damageComponent('physical', 'aoe', 0.15)],
    }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 92,
    initialCooldown: 4,
    cooldownTurns: 6,
    basePower: 14,
    powerPerRank: 7,
    attributeFactor: 1.6,
  },
  {
    skillId: 'pyro_ember',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 10,
    powerPerRank: 5,
    attributeFactor: 1.3,
    onHitDot: { element: 'fire', damagePerTurn: 4, durationTurns: 2 },
  },
  {
    skillId: 'arcane_surge',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 91,
    initialCooldown: 2,
    cooldownTurns: 4,
    basePower: 13,
    powerPerRank: 6,
    attributeFactor: 1.5,
  },
  {
    skillId: 'arcane_focus',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 87,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 9,
    powerPerRank: 5,
    attributeFactor: 1.2,
  },
  {
    skillId: 'inquisitor_judgment',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 4,
    basePower: 11,
    powerPerRank: 6,
    attributeFactor: 1.4,
  },
  {
    skillId: 'inquisitor_flame',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 83,
    initialCooldown: 0,
    cooldownTurns: 2,
    basePower: 8,
    powerPerRank: 4,
    attributeFactor: 1.1,
  },
  {
    skillId: 'reaver_cleave',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 0,
    cooldownTurns: 6,
    basePower: 12,
    powerPerRank: 6,
    attributeFactor: 1.0,
  },
];

const heroSkillMap = new Map(HERO_COMBAT_SKILL_CATALOG.map((skill) => [skill.skillId, skill]));

export function getHeroCombatSkill(skillId: string): CombatSkillDefinition | undefined {
  return heroSkillMap.get(skillId);
}

export function listHeroCombatSkills(hero: Hero): CombatSkillDefinition[] {
  const props = hero.toProps();

  return props.equippedSkillIds
    .filter((skillId): skillId is SkillId => Boolean(skillId))
    .filter((skillId) => (props.skillRanks[skillId] ?? 0) >= 1)
    .map((skillId) => heroSkillMap.get(skillId))
    .filter((skill): skill is CombatSkillDefinition => skill !== undefined);
}
