import { SkillDefinition } from './SkillDefinition';

export const SKILL_CATALOG: SkillDefinition[] = [
  // Universais
  {
    id: 'basic_attack',
    scope: 'universal',
    branch: 'offense',
    name: 'Ataque Básico',
    description: 'Golpe padrão usando o ATK do herói. Sempre ativo na batalha.',
    maxRank: 1,
    requirements: [],
    scaling: 'str',
    pointType: 'improvement',
  },
  {
    id: 'power_attack',
    scope: 'universal',
    branch: 'offense',
    name: 'Ataque Poderoso',
    description: 'Dano físico extra baseado em STR.',
    maxRank: 3,
    requirements: [{ type: 'hero_level', min: 2 }, { type: 'attribute', key: 'str', min: 8 }],
    scaling: 'str',
    pointType: 'improvement',
  },
  {
    id: 'evasion',
    scope: 'universal',
    branch: 'defense',
    name: 'Esquiva',
    description: 'Aumenta defesa com DEX.',
    maxRank: 3,
    requirements: [{ type: 'hero_level', min: 2 }, { type: 'attribute', key: 'dex', min: 8 }],
    scaling: 'dex',
    pointType: 'improvement',
  },
  {
    id: 'arcane_touch',
    scope: 'universal',
    branch: 'offense',
    name: 'Toque Arcano',
    description: 'Dano mágico leve baseado em INT.',
    maxRank: 3,
    requirements: [{ type: 'hero_level', min: 2 }, { type: 'attribute', key: 'int', min: 8 }],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'vitality',
    scope: 'universal',
    branch: 'defense',
    name: 'Vitalidade',
    description: 'Mais HP com STR.',
    maxRank: 2,
    requirements: [{ type: 'hero_level', min: 4 }, { type: 'attribute', key: 'str', min: 10 }],
    scaling: 'str',
    pointType: 'improvement',
  },
  // Knight
  {
    id: 'shield_bash',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Investida',
    description: 'Golpe pesado do cavaleiro.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'knight' }, { type: 'hero_level', min: 3 }],
    scaling: 'str',
    pointType: 'improvement',
  },
  {
    id: 'iron_skin',
    scope: 'class',
    heroClass: 'knight',
    branch: 'defense',
    name: 'Pele de Ferro',
    description: 'Reduz dano recebido.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'knight' },
      { type: 'skill_rank', skillId: 'shield_bash', minRank: 1 },
    ],
    scaling: 'str',
    pointType: 'improvement',
  },
  // Sorcerer
  {
    id: 'arcane_bolt',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Raio Arcano',
    description: 'Magia básica de dano.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'sorcerer' }, { type: 'hero_level', min: 2 }],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'fireball',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Bola de Fogo',
    description: 'Magia de fogo devastadora.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'sorcerer' },
      { type: 'skill_rank', skillId: 'arcane_bolt', minRank: 1 },
      { type: 'attribute', key: 'int', min: 12 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'mana_shield',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'defense',
    name: 'Escudo de Mana',
    description: 'Absorve parte do dano.',
    maxRank: 2,
    requirements: [
      { type: 'hero_class', heroClass: 'sorcerer' },
      { type: 'attribute', key: 'int', min: 10 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  // Priest
  {
    id: 'minor_heal',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Cura Menor',
    description: 'Cura o aliado mais ferido.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'priest' }, { type: 'hero_level', min: 2 }],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'blessing',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Bênção',
    description: 'Fortalece a party.',
    maxRank: 2,
    requirements: [
      { type: 'hero_class', heroClass: 'priest' },
      { type: 'skill_rank', skillId: 'minor_heal', minRank: 1 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'smite',
    scope: 'class',
    heroClass: 'priest',
    branch: 'offense',
    name: 'Castigo',
    description: 'Dano sagrado ao inimigo.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'priest' },
      { type: 'attribute', key: 'int', min: 10 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  // Ascensão — Knight Guardião
  {
    id: 'guardian_strike',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Golpe do Guardião',
    description: 'Ataque pesado da especialização defensiva.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_guardian' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_guardian',
  },
  {
    id: 'guardian_resolve',
    scope: 'class',
    heroClass: 'knight',
    branch: 'utility',
    name: 'Determinação',
    description: 'Cura aliado ferido com força interior.',
    maxRank: 2,
    requirements: [
      { type: 'ascension', ascensionId: 'knight_guardian' },
      { type: 'skill_rank', skillId: 'guardian_strike', minRank: 1 },
    ],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_guardian',
  },
  // Ascensão — Knight Devastador
  {
    id: 'reaver_cleave',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Fender',
    description: 'Golpe amplo de alta pressão.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_reaver' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_reaver',
  },
  {
    id: 'reaver_fury',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Fúria',
    description: 'Golpe brutal quando a batalha esquenta.',
    maxRank: 2,
    requirements: [
      { type: 'ascension', ascensionId: 'knight_reaver' },
      { type: 'skill_rank', skillId: 'reaver_cleave', minRank: 1 },
    ],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_reaver',
  },
  // Ascensão — Sorcerer Piromante
  {
    id: 'pyro_inferno',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Inferno',
    description: 'Chamas concentradas devastadoras.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_pyromancer' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_pyromancer',
  },
  {
    id: 'pyro_ember',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Brasa',
    description: 'Faíscas ardentes de suporte ofensivo.',
    maxRank: 2,
    requirements: [
      { type: 'ascension', ascensionId: 'sorcerer_pyromancer' },
      { type: 'skill_rank', skillId: 'pyro_inferno', minRank: 1 },
    ],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_pyromancer',
  },
  // Ascensão — Sorcerer Arcanista
  {
    id: 'arcane_surge',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Surto Arcano',
    description: 'Rajada de energia arcana pura.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcanist' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcanist',
  },
  {
    id: 'arcane_focus',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Foco Arcano',
    description: 'Feixe concentrado de poder mágico.',
    maxRank: 2,
    requirements: [
      { type: 'ascension', ascensionId: 'sorcerer_arcanist' },
      { type: 'skill_rank', skillId: 'arcane_surge', minRank: 1 },
    ],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcanist',
  },
  // Ascensão — Priest Oráculo
  {
    id: 'oracle_mend',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Restauração',
    description: 'Cura sagrada avançada.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_oracle' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_oracle',
  },
  {
    id: 'oracle_sanctuary',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Santuário',
    description: 'Proteção curativa intensa.',
    maxRank: 2,
    requirements: [
      { type: 'ascension', ascensionId: 'priest_oracle' },
      { type: 'skill_rank', skillId: 'oracle_mend', minRank: 1 },
    ],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_oracle',
  },
  // Ascensão — Priest Inquisidor
  {
    id: 'inquisitor_judgment',
    scope: 'class',
    heroClass: 'priest',
    branch: 'offense',
    name: 'Julgamento',
    description: 'Castigo divino devastador.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_inquisitor' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_inquisitor',
  },
  {
    id: 'inquisitor_flame',
    scope: 'class',
    heroClass: 'priest',
    branch: 'offense',
    name: 'Chama Sagrada',
    description: 'Fogo sagrado contra o inimigo.',
    maxRank: 2,
    requirements: [
      { type: 'ascension', ascensionId: 'priest_inquisitor' },
      { type: 'skill_rank', skillId: 'inquisitor_judgment', minRank: 1 },
    ],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_inquisitor',
  },
  // Monstros — acervo unificado (heróis podem desbloquear no futuro)
  { id: 'wild_bite', scope: 'monster', branch: 'offense', name: 'Mordida Selvagem', description: 'Mordida feroz do predador.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'goblin_stab', scope: 'monster', branch: 'offense', name: 'Facada', description: 'Golpe traiçoeiro com dano extra.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'orc_smash', scope: 'monster', branch: 'offense', name: 'Pancada', description: 'Golpe pesado esmagador.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'poison_spit', scope: 'monster', branch: 'offense', name: 'Cuspe Venenoso', description: 'Veneno corrosivo à distância.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'ground_slam', scope: 'monster', branch: 'offense', name: 'Pancada Sísmica', description: 'Golpe de área que treme o chão.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'regenerate', scope: 'monster', branch: 'utility', name: 'Regeneração', description: 'Recupera vida ao longo do combate.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'slime_acid', scope: 'monster', branch: 'offense', name: 'Ácido', description: 'Corrói o alvo com dano mágico.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'wraith_drain', scope: 'monster', branch: 'offense', name: 'Drenar Vida', description: 'Dreno mágico de vitalidade.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'wraith_curse', scope: 'monster', branch: 'offense', name: 'Maldição', description: 'Reduz a defesa do alvo.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'dragon_breath', scope: 'monster', branch: 'offense', name: 'Baforada', description: 'Fogo em área devastador.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'dragon_bite', scope: 'monster', branch: 'offense', name: 'Mordida', description: 'Mordida devastadora.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'saci_fire', scope: 'monster', branch: 'offense', name: 'Chama Elemental', description: 'Fogo concentrado no alvo.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'saci_wind', scope: 'monster', branch: 'offense', name: 'Rajada de Vento', description: 'Vento cortante em área.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
];

export function getSkillById(skillId: string): SkillDefinition | undefined {
  return SKILL_CATALOG.find((skill) => skill.id === skillId);
}

export function getSkillsForHero(heroClass: string, ascensionId: string | null): SkillDefinition[] {
  return SKILL_CATALOG.filter((skill) => {
    if (skill.pointType === 'ascension') {
      return ascensionId !== null && skill.ascensionId === ascensionId;
    }
    if (skill.scope === 'universal') return true;
    if (skill.scope === 'class' && skill.heroClass === heroClass) return true;
    if (skill.scope === 'monster') return false;
    return false;
  });
}
