import { UpgradeDefinition } from './UpgradeDefinition';

export const UPGRADE_CATALOG: UpgradeDefinition[] = [
  {
    id: 'auto_battle_1',
    feature: 'auto_battle',
    level: 1,
    branch: 'combat',
    name: 'Auto-batalha I',
    description: 'Desbloqueia auto-batalha em 1x nas Configurações.',
    cost: 40,
    requirements: [{ type: 'min_stage', value: 2 }],
  },
  {
    id: 'auto_battle_2',
    feature: 'auto_battle',
    level: 2,
    branch: 'combat',
    name: 'Auto-batalha II',
    description: 'Desbloqueia velocidade 2x na auto-batalha.',
    cost: 120,
    requirements: [
      { type: 'upgrade_level', feature: 'auto_battle', minLevel: 1 },
      { type: 'min_battles_won', value: 10 },
    ],
  },
  {
    id: 'auto_battle_3',
    feature: 'auto_battle',
    level: 3,
    branch: 'combat',
    name: 'Auto-batalha III',
    description: 'Desbloqueia velocidade 3x na auto-batalha.',
    cost: 300,
    requirements: [
      { type: 'upgrade_level', feature: 'auto_battle', minLevel: 2 },
      { type: 'min_stage', value: 6 },
    ],
  },
  {
    id: 'background_tick_1',
    feature: 'background_tick',
    level: 1,
    branch: 'combat',
    name: 'Tick idle I',
    description: 'O jogo avança em background mesmo com o painel fechado.',
    cost: 80,
    requirements: [{ type: 'min_stage', value: 3 }],
  },
  {
    id: 'background_tick_2',
    feature: 'background_tick',
    level: 2,
    branch: 'combat',
    name: 'Tick idle II',
    description: 'Tick em background 2x mais frequente.',
    cost: 200,
    requirements: [
      { type: 'upgrade_level', feature: 'background_tick', minLevel: 1 },
      { type: 'min_stage', value: 5 },
    ],
  },
  {
    id: 'auto_open_chests_1',
    feature: 'auto_open_chests',
    level: 1,
    branch: 'chests',
    name: 'Auto-abrir baús I',
    description: 'Abre baús automaticamente quando disponíveis.',
    cost: 60,
    requirements: [
      { type: 'upgrade_level', feature: 'auto_battle', minLevel: 1 },
      { type: 'min_stage', value: 3 },
    ],
  },
  {
    id: 'open_all_chests_1',
    feature: 'open_all_chests',
    level: 1,
    branch: 'chests',
    name: 'Abrir todos I',
    description: 'Desbloqueia o botão Abrir Todos no footer.',
    cost: 100,
    requirements: [{ type: 'upgrade_level', feature: 'auto_open_chests', minLevel: 1 }],
  },
  {
    id: 'open_all_chests_2',
    feature: 'open_all_chests',
    level: 2,
    branch: 'chests',
    name: 'Abrir todos II',
    description: 'Auto-abrir prioriza abrir todos quando há 2+ baús.',
    cost: 180,
    requirements: [
      { type: 'upgrade_level', feature: 'open_all_chests', minLevel: 1 },
      { type: 'min_chests_opened', value: 5 },
    ],
  },
  {
    id: 'optimize_loadout_1',
    feature: 'optimize_loadout',
    level: 1,
    branch: 'equipment',
    name: 'Otimizar equipe I',
    description: 'Desbloqueia o botão Otimizar equipe.',
    cost: 90,
    requirements: [
      { type: 'min_stage', value: 3 },
      { type: 'min_battles_won', value: 8 },
    ],
  },
  {
    id: 'optimize_loadout_2',
    feature: 'optimize_loadout',
    level: 2,
    branch: 'equipment',
    name: 'Otimizar equipe II',
    description: 'Otimização disponível no loot em lote dos baús.',
    cost: 220,
    requirements: [
      { type: 'upgrade_level', feature: 'optimize_loadout', minLevel: 1 },
      { type: 'min_stage', value: 5 },
    ],
  },
  {
    id: 'auto_equip_loot_1',
    feature: 'auto_equip_loot',
    level: 1,
    branch: 'equipment',
    name: 'Auto-equipar I',
    description: 'Equipa loot recomendado sem abrir modal.',
    cost: 150,
    requirements: [{ type: 'upgrade_level', feature: 'optimize_loadout', minLevel: 1 }],
  },
  {
    id: 'auto_equip_loot_2',
    feature: 'auto_equip_loot',
    level: 2,
    branch: 'equipment',
    name: 'Auto-equipar II',
    description: 'Auto-equipar sem notificações (silencioso).',
    cost: 280,
    requirements: [
      { type: 'upgrade_level', feature: 'auto_equip_loot', minLevel: 1 },
      { type: 'upgrade_level', feature: 'auto_open_chests', minLevel: 1 },
    ],
  },
  {
    id: 'log_filter_1',
    feature: 'log_filter',
    level: 1,
    branch: 'qol',
    name: 'Log resumido I',
    description: 'Filtra o log para eventos importantes.',
    cost: 35,
    requirements: [{ type: 'min_stage', value: 2 }],
  },
  {
    id: 'shop_refresh_1',
    feature: 'shop_refresh',
    level: 1,
    branch: 'economy',
    name: 'Renovar loja I',
    description: 'Desbloqueia renovar loja (2x por stage).',
    cost: 70,
    requirements: [{ type: 'min_stage', value: 4 }],
  },
  {
    id: 'shop_refresh_2',
    feature: 'shop_refresh',
    level: 2,
    branch: 'economy',
    name: 'Renovar loja II',
    description: 'Até 5 renovações por stage.',
    cost: 160,
    requirements: [
      { type: 'upgrade_level', feature: 'shop_refresh', minLevel: 1 },
      { type: 'min_stage', value: 6 },
    ],
  },
  {
    id: 'shop_refresh_3',
    feature: 'shop_refresh',
    level: 3,
    branch: 'economy',
    name: 'Renovar loja III',
    description: 'Até 8 renovações por stage com 15% de desconto.',
    cost: 320,
    requirements: [
      { type: 'upgrade_level', feature: 'shop_refresh', minLevel: 2 },
      { type: 'min_battles_won', value: 20 },
    ],
  },
  {
    id: 'battle_skill_slot_2',
    feature: 'battle_skill_slots',
    level: 1,
    branch: 'combat',
    name: 'Slot de skill II',
    description: 'Desbloqueia o 2º slot de skill ativa na batalha.',
    cost: 60,
    requirements: [{ type: 'min_hero_level', value: 3 }],
  },
  {
    id: 'battle_skill_slot_3',
    feature: 'battle_skill_slots',
    level: 2,
    branch: 'combat',
    name: 'Slot de skill III',
    description: 'Desbloqueia o 3º slot de skill ativa na batalha.',
    cost: 150,
    requirements: [
      { type: 'upgrade_level', feature: 'battle_skill_slots', minLevel: 1 },
      { type: 'min_hero_level', value: 6 },
    ],
  },
];

export function getUpgradeById(id: string): UpgradeDefinition | undefined {
  return UPGRADE_CATALOG.find((entry) => entry.id === id);
}
